### ISSUE TITLE
needs install dependency

### ISSUE THREAD

**Issue by UziTech** [AtomLinter/linter-htmlhint#164]
![image](https://user-images.githubusercontent.com/97994/30431797-64b5b83a-9925-11e7-97ee-ab9ee882162f.png)

This pops up when [`atom-ide-ui`](https://atom.io/packages/atom-ide-ui) is installed and `linter` is disabled.

I'm pretty sure this is happening on all linter packages.

**Comment by Arcanemagus** [comment]
Unfortunately there is nothing that can be done about this with Atom's current package ecosystem. There is no way in Atom to ensure that there is a compatible consumer of the service provided, so for now all the providers force the installation of `linter`. You can simply say "Never" to that prompt, but be warned that there are still some providers using an ancient version of `atom-package-deps` that doesn't prompt so you might need to just disable `linter` if that is the direction you are aiming for.

The last time any work was done on fixing this major problem was back in https://github.com/atom/apm/pull/387, but that was closed because "the interface needs to be figured out first". I'll put another bump into that thread to hopefully bring it up that this is still a major issue...

Note that `atom-ide-ui` is still very much in beta (I'm amazed they released it now with how many bugs it has) and can't even be used on the stable release of Atom, so until it is eventually integrated directly into Atom there isn't any reason to remove the check for `linter`.
