### ISSUE TITLE
linter-htmlhint doesn't allow CDATA sections

### ISSUE THREAD

**Issue by garretwilson** [AtomLinter/linter-htmlhint#70]
I am using XHTML5 files. (Basically just HTML5 with XML syntax. Yes, it's allowed.)

linter-htmlhint thinks this is a problem with this:

````xml
		<pre><code  class="language-java"><![CDATA[@ApplicationPath("/foo/)
public class FooApplication extends Application {

  @Override
  public Set<Class<?>> getClasses() {
    return ImmutableSet.of(BarResourceService.class);  //implementation of BarResource
  }

}]]></code></pre>
````

It thinks I should escape the `<` characters. But I don't need to escape the `<` characters in a CDATA section.

* Yes, I understand that @Arcanemagus is going to tell me that it's an HTMLHint problem, not a linter-htmlhing problem.
* Yes, I understand that @yaniswang is going to tell me that HTMLHint doesn't support XML.
* Yes, I realize that all these linters and formatters are buggy and broken.
* Yes, I realize I'm just going to have to write my own.

OK, you can close this now I suppose. I already know how it's going to go.

**Comment by garretwilson** [comment]
BTW, I'm only using CDATA sections so that it can work with BlueGriffon, which doesn't correctly encode `<` if I don't use a CDATA section, which breaks my files.

https://github.com/therealglazou/bluegriffon/issues/10

See, all these bugs catch me either way I go.

**Comment by Arcanemagus** [comment]
As you correctly surmised, closing this as it isn't an issue with `linter-htmlhint`. :stuck_out_tongue:

Have you looked into [linter-xmllint](https://github.com/AtomLinter/linter-xmllint)? @dirk-thomas does a great job of maintaining that linter. It sounds like you might want to tell `linter-htmlhint` to ignore those errors and let `linter-xmllint` handle anything invalid in there.

**Comment by garretwilson** [comment]
>  It sounds like you might want to tell `linter-htmlhint` to ignore those errors ...

And how would I do that, pray tell?

[rant]Methinks everybody is just passing the buck... Nobody wants to claim it as their problem. The fact is that there exists no plugin that can correctly lint an XHTML5 file on Atom. There exists no plugin that can even correctly format an XHTML5 file. (And please let's not get into a discussion about what XHTML5 is, as everybody seems to want to do; you can look it up in the HTML5 spec.)[/rant]

**Comment by johnwebbcole** [comment]
I think @Arcanemagus  meant to say that you should tell [htmlhint](http://htmlhint.com) about the linting issue.

Before you rant too much, remember that `linter-htmlhint` and many other `linter` plugins don't actually do the linting.  We spawn an external linter, `htmlhint` in this case, and parse the output into something usable by `linter` and `atom`.  The source of this plugin is only 85 lines, around the size of a two rules in `htmlhint`.  There is nothing in this plugin to add or remove XHTML compatibility.

I'd suggest trying `linter-tidy` since some versions of `tidy` do support XHTML.  Though I've stopped using `tidy` in favor of `htmlhint` due to other issues.

Issues dealing with `atom` and `linter-htmlhint` should be directed here.  Linting issues should be directed at [htmlhint](http://htmlhint.com).

**Comment by garretwilson** [comment]
> remember that linter-htmlhint and many other linter plugins don't actually do the linting.

Right. That's what all the plugin authors say. But they could put some effort into adding workarounds to the underlying linters if they really cared. I'm just saying... that I get the runaround, and eventually I'll just have to write this stuff myself.

> I'd suggest trying linter-tidy since some versions of tidy do support XHTML.

...except that linter-tidy is broken, too:

https://github.com/AtomLinter/linter-tidy/issues/24

Like I said, there exists no plugin that can correctly lint an XHTML5 file on Atom---or even format HTML correctly. I know of which I speak. I didn't start ranting on a whim.

**Comment by Arcanemagus** [comment]
@johnwebbcole @garretwilson has already filed https://github.com/yaniswang/HTMLHint/issues/102 for support of this in `htmlhint` without much luck (yet).

And for some reason I had remembered this plugin as one that allows ignoring specific errors from the output of the linter, but looking over the code this doesn't do that so I was mistaken there, sorry!

@garretwilson as for your "Passing the buck" comment, yes that's absolutely what is going on here since this plugin, and _all_ the other `linter-*` plugins _just_ act as translators between the output of their specific linter and the message format the `linter` package expects. They can change some options in how the linter is ran, but have _nothing_ to do with the actual linting process which is what your issue is here. I know I'm sounding like a broken record, but most of the issues you have filed around here have nothing to do with the service provider plugins :confused:.

What sort of "workaround" are you expecting here? Translating your source code into something that htmlhint knows how to parse before sending it over there?

**Comment by garretwilson** [comment]
> What sort of "workaround" are you expecting here?

Off the top of my head? I know nothing about the linter API, but I assume that at some point in the linter-htmlhint code you get to some point knowing 1) the position within the text buffer a supposed error occurred, and 2) what that error was. My first brainstorm would be to add code like this:

````
ignoreError = false;
//fix-up for htmlhint lack of XML support
if(error is for unencoded characters like '<') {
  search backwards in the buffer position for the first occurrence of "<![CDATA["
  if("<![CDATA[" is found) {
    search forward to see if "]]>" occurs before the error position
    if("]]>" was not found) {
      ignoreError
   }
}
````

I'm sure there are five ways to work around this, some of them probably better than this off-the-top-of-my-head idea.

You are right; this is really HTMLHint's fault, but @yaniswang can't even be bothered to check for an XML declaration, so good luck getting that working.

My point is that nothing works. I'm sure your plugin is doing everything it's supposed to be doing. Everybody will say that they're doing everything they are supposed to be doing. But nothing works. HTMLHint doesn't work with XML. linter-tidy is broken. js-beautify (oh, we went through the plugin vs library thing there) screws up the line endings. The js-beautify library is based on a model that doesn't allow you to indicate something is inline without also saying that it shouldn't be formatted. BlueGriffon corrupts line endings and doesn't encode things like '<' in certain circumstances. It's all junk. Nobody writes good software nowadays---they just throw things together.

I could go on all night. I could link to all the bugs that have been filed that no one will ever get to. But... I've wasted too much of both our time already.

You can close this, as I mentioned in the first comment of this issue. Good night.

**Comment by garretwilson** [comment]
P.S. Yes, @Arcanemagus, I realize that I'm not helping anyone with these rants here and that my only option really is just to write all this stuff myself. In fact I'm training a team of software developers now (I can't rewrite everything myself) and hopefully they will be able to address some of this stuff for me in a few months. The problem is that all the course materials I'm writing myself... in XHTML5! So you can imagine the frustration when I can't even find an editor that can lint and format! Arg, the irony...

All the best. Good luck on your plugin.
